import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  annotate_findings_in_diff,
  path_in_diff,
  resolve_ast_scan_scope,
} from "../open_ast.ts";

const DIFF = [
  "src/main/java/com/example/SecurityCodeBiz.java",
  "src/main/java/com/example/IntelligenceAdaptor.java",
];

describe("AST PR/diff scope", () => {
  it("matches repo-relative and suffix paths against diff.files", () => {
    assert.equal(path_in_diff("src/main/java/com/example/SecurityCodeBiz.java", DIFF), true);
    assert.equal(
      path_in_diff("/tmp/clone/src/main/java/com/example/SecurityCodeBiz.java", DIFF),
      true,
    );
    assert.equal(path_in_diff("src/main/java/com/example/StockUtil.java", DIFF), false);
    assert.equal(path_in_diff("SecurityCodeBiz.java", DIFF), true);
  });

  it("defaults a taskId PR scan to changed files", () => {
    const scope = resolve_ast_scan_scope({
      taskId: 1,
      taskDiffFiles: DIFF,
    });
    assert.equal(scope.scanMode, "changed_files");
    assert.deepEqual(scope.scanFiles, DIFF);
    assert.equal(scope.warning, undefined);
  });

  it("keeps whole-repo when --full-repo is set and still annotates the diff", () => {
    const scope = resolve_ast_scan_scope({
      taskId: 1,
      fullRepo: true,
      taskDiffFiles: DIFF,
    });
    assert.equal(scope.scanMode, "full_repo");
    assert.equal(scope.scanFiles, null);
    assert.deepEqual(scope.annotateDiffFiles, DIFF);
  });

  it("uses explicit --diff-files as the scan set", () => {
    const scope = resolve_ast_scan_scope({
      diffFiles: ["a.java"],
      taskDiffFiles: DIFF,
    });
    assert.equal(scope.scanMode, "changed_files");
    assert.deepEqual(scope.scanFiles, ["a.java"]);
  });

  it("falls back to full-repo with a warning when changed-only has no files", () => {
    const scope = resolve_ast_scan_scope({
      taskId: 1,
      changedOnly: true,
      taskDiffFiles: [],
    });
    assert.equal(scope.scanMode, "full_repo");
    assert.ok(scope.warning);
  });

  it("tags out-of-diff findings as auto-dismissable", () => {
    const findings = annotate_findings_in_diff(
      [
        { filePath: "src/main/java/com/example/SecurityCodeBiz.java", ruleId: "R1" },
        { filePath: "src/main/java/com/example/StockUtil.java", ruleId: "R2" },
      ],
      DIFF,
    );
    assert.equal(findings[0].inDiff, true);
    assert.equal(findings[1].inDiff, false);
  });

  it("does not silently drop in-diff hits when annotating a mixed full-repo result", () => {
    const findings = annotate_findings_in_diff(
      [
        { filePath: "src/main/java/com/example/IntelligenceAdaptor.java", autoGenerated: false },
        { filePath: "src/main/java/com/other/Legacy.java", autoGenerated: false },
        { filePath: "src/main/java/com/example/Gen.java", autoGenerated: true },
      ],
      DIFF,
    );
    const verify = findings.filter((f) => !f.autoGenerated && f.inDiff !== false);
    const dismiss = findings.filter((f) => f.autoGenerated || f.inDiff === false);
    assert.equal(verify.length, 1);
    assert.equal(verify[0].filePath, "src/main/java/com/example/IntelligenceAdaptor.java");
    assert.equal(dismiss.length, 2);
  });
});
