import { fmtNumber } from './text.mjs';

const KIND_ZH = {
  class: '类', function: '函数', method: '方法', constructor: '构造函数', interface: '接口', struct: '结构体',
  type: '类型', type_alias: '类型别名', enum: '枚举', const: '常量', constant: '常量', variable: '变量',
  field: '字段', property: '属性', module: '模块', namespace: '命名空间', trait: 'trait', impl: '实现', macro: '宏',
};
const KIND_EN = { type_alias: 'type alias' };
const LAYER = {
  zh: { entry: '入口', application: '应用', domain: '领域', storage: '存储' },
  en: { entry: 'Entry', application: 'Application', domain: 'Domain', storage: 'Storage' },
};

export function strings(lang) {
  const n = (v) => fmtNumber(v, lang);
  if (lang === 'en') {
    return {
      htmlLang: 'en',
      brand: 'Code Wiki',
      skip: 'Skip to content',
      search: 'Search modules, symbols, files',
      searchShort: 'Search',
      legendMinor: (n) => `${n} weaker ${n === 1 ? 'call is' : 'calls are'} hidden; hover a module to see all of its calls`,
      scrollHint: 'Swipe sideways to see the whole map',
      searchEmpty: 'No match',
      menu: 'Contents',
      theme: 'Switch light / dark',
      navOverview: 'Overview',
      navStart: 'Where to start',
      navWhat: 'What this is',
      navMap: 'Module map',
      navModules: 'Modules',
      navStandalone: 'Standalone',
      navAbout: 'About this report',
      eyebrow: 'Architecture wiki',
      facts: (m) => [
        [n(m.modules.length), m.modules.length === 1 ? 'module' : 'modules'],
        [n(m.groups.length), m.groups.length === 1 ? 'group that calls each other' : 'groups that call each other'],
        [n(m.standalone.length), 'standalone'],
      ],
      coverage: (pct) => [`${pct}%`, 'of indexed code'],
      commit: 'Commit',
      noModel: 'No model call for facts',
      draft: 'Draft: the explanations are not written yet. Names and descriptions below are rule-based placeholders.',
      dirty: 'The working tree had uncommitted changes when this was built; it may not match the commit exactly.',
      partial: (shown, pct) => `These ${shown} modules cover ${pct}% of indexed code. Smaller modules are not included.`,
      truncated: (shown, total) => `Only the ${shown} largest of ${total} modules are included.`,
      startTitle: 'Where to start',
      startLead: 'Each path only follows real calls: every step calls the next one, or is called by it.',
      autoGuide: 'Suggested from the call graph',
      autoGuideTitle: (label) => `Start with ${label}`,
      stepCalls: (a, b, w) => (w ? `${a} → ${b}: ${n(w)} references` : `${a} → ${b}`),
      whatTitle: 'What this is',
      mapTitle: 'Module map',
      mapLead: 'Each box is a group of modules that call each other. Arrows point from caller to callee; thicker lines mean more references; a double arrow means both directions. Select a module to read about it.',
      legendHub: 'Hub: the most connected module in its group',
      legendSize: 'Bar under a name: size relative to the largest module',
      legendDashed: 'Dashed line: listed as related, count unknown',
      graphLabel: 'Module map',
      standaloneBox: 'Standalone',
      modulesTitle: 'Modules',
      modulesLead: 'Grouped the same way as the map. Open a module for its calls, public API, key flows, and files.',
      expandAll: 'Expand all',
      collapseAll: 'Collapse all',
      groupCount: (k) => `${n(k)} modules`,
      groupAuto: (names) => `Around ${names.join(', ')}`,
      hub: 'Hub',
      layer: (code) => LAYER.en[code] || '',
      sizeShort: (v) => n(v),
      sizeLong: (v) => `${n(v)} symbols`,
      calls: 'Calls',
      calledBy: 'Called by',
      api: 'Public API',
      flows: 'Key flows',
      files: 'Files',
      moreFiles: (k) => `${n(k)} more`,
      refs: (w) => (w ? `${n(w)} refs` : 'count unknown'),
      usedBy: (k) => `used ${n(k)}×`,
      moreSteps: (k) => `+${n(k)} more`,
      kind: (k) => KIND_EN[k] || k,
      defs: (k) => `${n(k)} definitions`,
      none: 'None in this export',
      outside: (ids) => `Also related to ${ids.join(', ')}, which is outside this report.`,
      standaloneTitle: 'Standalone modules',
      standaloneLead: 'No calls to or from the other modules in this report. Usually a standalone script, tool, or demo. Read the main paths first.',
      aboutTitle: 'About this report',
      aboutFacts: 'Facts on this page come from the local CodexQA index, exported without calling a model. The explanations were written by a coding agent from those facts.',
      glossary: [
        ['Module', 'A tightly connected group of code found by community detection (Leiden) on the symbol call graph. It is not a folder and not a change-history grouping.'],
        ['References', 'Static calls and references counted across modules. Not runtime traffic.'],
        ['Size', 'Number of symbols (functions, classes, types…) in the module.'],
        ['Standalone', 'No counted calls to other modules here. Code can still be reached through config, CLI, or dynamic loading.'],
      ],
      commands: 'Commands',
      generated: (when) => `Generated ${when}`,
      fallbackRole: (m) => (m.files.length ? `Mainly ${m.files.slice(0, 2).map((f) => f.split('/').pop()).join(', ')}` : ''),
      fallbackOverview: (m) => `This report covers ${n(m.modules.length)} modules: ${n(m.groups.length)} groups that call each other and ${n(m.standalone.length)} standalone.`,
      edgeTip: (e, label) => {
        const a = `${e.from} ${label(e.from)}`;
        const b = `${e.to} ${label(e.to)}`;
        if (!e.known) return `${a} ↔ ${b}: related, count unknown`;
        return `${a} → ${b}: ${n(e.weight)} references${e.back ? `; back ${n(e.back)}` : ''}`;
      },
      nodeTip: (m, name) => `${m.id} ${name} · ${n(m.size)} symbols`,
      empty: 'This export has no modules. Check the index with `codexqa stats <repo>`.',
    };
  }
  return {
    htmlLang: 'zh-CN',
    brand: 'Code Wiki',
    skip: '跳到正文',
    search: '搜索模块、符号、文件',
    searchShort: '搜索',
    legendMinor: (n) => `另有 ${n} 条较弱的调用没画出，悬停模块可看它的全部调用`,
    scrollHint: '左右滑动查看完整的图',
    searchEmpty: '没有匹配',
    menu: '目录',
    theme: '切换白天 / 黑夜',
    navOverview: '概览',
    navStart: '从哪读起',
    navWhat: '它是什么',
    navMap: '架构图',
    navModules: '模块',
    navStandalone: '独立模块',
    navAbout: '关于这份报告',
    eyebrow: '架构 Wiki',
    facts: (m) => [
      [n(m.modules.length), '个模块'],
      [n(m.groups.length), '组互相调用'],
      [n(m.standalone.length), '个独立'],
    ],
    coverage: (pct) => [`${pct}%`, '索引代码已覆盖'],
    commit: '提交',
    noModel: '事实部分未调用模型',
    draft: '草稿：说明文字还没写完，下面的名称和描述是按规则生成的占位内容。',
    dirty: '生成时工作区有未提交的改动，内容可能和这个提交不完全一致。',
    partial: (shown, pct) => `这 ${shown} 个模块只覆盖了索引中 ${pct}% 的代码，较小的模块没有收录。`,
    truncated: (shown, total) => `共 ${total} 个模块，这里只收录了规模最大的 ${shown} 个。`,
    startTitle: '从哪读起',
    startLead: '每条路径只沿真实存在的调用走：相邻两步之间一定有调用关系。',
    autoGuide: '按调用关系自动推荐',
    autoGuideTitle: (label) => `从 ${label} 读起`,
    stepCalls: (a, b, w) => (w ? `${a} → ${b}：${n(w)} 处引用` : `${a} → ${b}`),
    whatTitle: '它是什么',
    mapTitle: '架构图',
    mapLead: '每个框是一组互相调用的模块。箭头从调用方指向被调用方，线越粗引用越多，双箭头表示互相调用。点模块看说明。',
    legendHub: '枢纽：组内连接最多的模块',
    legendSize: '名称下的细条：相对最大模块的规模',
    legendDashed: '虚线：导出里列为相关，但没有引用数',
    graphLabel: '架构图',
    standaloneBox: '独立模块',
    modulesTitle: '模块',
    modulesLead: '分组和架构图一致。展开模块看它调用谁、被谁调用、对外接口、关键流程和文件。',
    expandAll: '全部展开',
    collapseAll: '全部收起',
    groupCount: (k) => `${n(k)} 个模块`,
    groupAuto: (names) => `围绕 ${names.join('、')} 的一组`,
    hub: '枢纽',
    layer: (code) => LAYER.zh[code] || '',
    sizeShort: (v) => n(v),
    sizeLong: (v) => `${n(v)} 个符号`,
    calls: '调用',
    calledBy: '被调用',
    api: '对外接口',
    flows: '关键流程',
    files: '文件',
    moreFiles: (k) => `其余 ${n(k)} 个`,
    refs: (w) => (w ? `${n(w)} 处引用` : '引用数未知'),
    usedBy: (k) => `被 ${n(k)} 处调用`,
    moreSteps: (k) => `另有 ${n(k)} 步`,
    kind: (k) => KIND_ZH[k] || k,
    defs: (k) => `${n(k)} 处同名定义`,
    none: '本次导出里没有',
    outside: (ids) => `另外还和 ${ids.join('、')} 有关，它们不在这份报告里。`,
    standaloneTitle: '独立模块',
    standaloneLead: '和这份报告里的其他模块没有调用关系，多半是独立脚本、工具或演示。先读主链路，用到时再看。',
    aboutTitle: '关于这份报告',
    aboutFacts: '页面上的事实（模块、规模、调用、接口、文件）来自本地 CodexQA 索引，导出时没有调用模型。说明文字由 Coding Agent 依据这些事实撰写。',
    glossary: [
      ['模块', '在符号调用图上用社区检测（Leiden）聚出的一组联系紧密的代码。不等于目录，也不代表「经常一起修改」。'],
      ['引用数', '静态分析统计的跨模块调用和引用处数，不是线上调用次数。'],
      ['规模', '模块里的符号（函数、类、类型等）数量。'],
      ['独立', '和这里的其他模块没有统计到调用。代码仍可能通过配置、命令行或动态加载被用到。'],
    ],
    commands: '生成命令',
    generated: (when) => `生成于 ${when}`,
    fallbackRole: (m) => (m.files.length ? `主要文件：${m.files.slice(0, 2).map((f) => f.split('/').pop()).join('、')}` : ''),
    fallbackOverview: (m) => `这份报告收录 ${n(m.modules.length)} 个模块：${n(m.groups.length)} 组互相调用，另有 ${n(m.standalone.length)} 个独立模块。`,
    edgeTip: (e, label) => {
      const a = `${e.from} ${label(e.from)}`;
      const b = `${e.to} ${label(e.to)}`;
      if (!e.known) return `${a} ↔ ${b}：列为相关，没有引用数`;
      return `${a} → ${b}：${n(e.weight)} 处引用${e.back ? `；反向 ${n(e.back)} 处` : ''}`;
    },
    nodeTip: (m, name) => `${m.id} ${name} · ${n(m.size)} 个符号`,
    empty: '这次导出没有模块。先用 `codexqa stats <repo>` 检查索引。',
  };
}
