#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Local knowledge-pack bootstrap: scan a user-provided knowledge directory or
cloned repo and write {run_dir}/knowledge/index.md.

When the user explicitly provides a Git URL, shallow-clone first via
fetch_knowledge_git.py, then scan Markdown inside the repo.
Does not call an external knowledge-base retrieval Skill. When no source is
provided, write an empty index so the main flow can continue.
"""

from __future__ import annotations

from py_version import require_py310

require_py310()

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from fetch_knowledge_git import fetch, split_url_and_ref, validate_git_url, validate_ref


DOC_EXTS = {".md", ".markdown", ".txt"}
SKIP_DIR_NAMES = {".git", ".svn", "node_modules", "__pycache__", ".idea", ".venv"}
MAX_FILES = 500
MAX_DEPTH = 6
H1_RE = re.compile(r"^#\s+(.+)$", re.M)


def infer_dimension(rel_path: str) -> str:
    text = rel_path.lower()
    mapping = (
        ("规则", "Business rules"),
        ("rule", "Business rules"),
        ("流程", "Business flows"),
        ("flow", "Business flows"),
        ("process", "Business flows"),
        ("术语", "Business terms"),
        ("term", "Business terms"),
        ("架构", "System architecture"),
        ("architecture", "System architecture"),
        ("接口", "Services and APIs"),
        ("api", "Services and APIs"),
        ("testdata", "Test-data setup process"),
        ("test-data", "Test-data setup process"),
        ("数据", "Data models"),
        ("data", "Data models"),
        ("缺陷", "Defect patterns"),
        ("defect", "Defect patterns"),
        ("风险", "Historical risks"),
        ("risk", "Historical risks"),
        ("策略", "Test strategy"),
        ("strategy", "Test strategy"),
        ("样板", "Case samples"),
        ("sample", "Case samples"),
        ("标签", "Tag strategy"),
        ("tag", "Tag strategy"),
        ("造数", "Test-data setup process"),
        ("规范", "Case-writing standards"),
        ("standard", "Case-writing standards"),
        ("spec", "Case-writing standards"),
    )
    for needle, dimension in mapping:
        if needle in text:
            return dimension
    return "Uncategorized"


def iter_docs(source: Path) -> list[Path]:
    docs: list[Path] = []
    for path in source.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in DOC_EXTS:
            continue
        rel_parts = path.relative_to(source).parts
        if len(rel_parts) - 1 > MAX_DEPTH:
            continue
        if any(part in SKIP_DIR_NAMES or part.startswith(".") for part in rel_parts[:-1]):
            continue
        docs.append(path)
        if len(docs) >= MAX_FILES:
            break
    return sorted(docs)


def title_of(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")[:4000]
    except OSError:
        return path.stem
    match = H1_RE.search(text)
    return match.group(1).strip() if match else path.stem


def write_index(output_dir: Path, rows: list[dict], source: str) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Local knowledge index",
        "",
        "> Generated by `bootstrap_knowledge.py` from a local directory or a user-provided Git repo. Does not call a retrieval Skill.",
        "",
        f"- Source: {source or '(no local knowledge directory provided)'}",
        f"- Entry count: {len(rows)}",
        "",
        "| Title | Knowledge dimension | Knowledge level | Local knowledge file path | Source |",
        "|------|----------|----------|------------------|------|",
    ]
    if rows:
        for row in rows:
            lines.append(
                "| {title} | {dimension} | L1 | {path} | {source} |".format(**row)
            )
    else:
        lines.append("| (empty) | — | — | — | No local knowledge pack provided |")
    lines.append("")
    index_path = output_dir / "index.md"
    index_path.write_text("\n".join(lines), encoding="utf-8")
    return index_path


def bootstrap(
    output_dir: Path,
    source: Path | None,
    git_url: str = "",
    git_ref: str = "",
) -> dict:
    rows: list[dict] = []
    copied = 0
    fetch_info: dict | None = None
    if git_url:
        url, inline_ref = split_url_and_ref(git_url)
        valid_url = validate_git_url(url)
        valid_ref = validate_ref(git_ref or inline_ref)
        if valid_url is None or valid_ref is None:
            write_index(output_dir, [], git_url)
            manifest = {
                "ok": False,
                "error": "invalid git url" if valid_url is None else "invalid git ref",
                "indexPath": str(output_dir / "index.md"),
                "entryCount": 0,
                "copied": 0,
                "source": "",
                "gitUrl": git_url,
                "empty": True,
            }
            (output_dir / "knowledge-manifest.json").write_text(
                json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            return manifest
        fetch_info = fetch(valid_url, output_dir / "repo", valid_ref or "")
        if not fetch_info.get("ok"):
            write_index(output_dir, [], git_url)
            manifest = {
                "ok": False,
                "error": fetch_info.get("error", "git clone failed"),
                "indexPath": str(output_dir / "index.md"),
                "entryCount": 0,
                "copied": 0,
                "source": "",
                "gitUrl": valid_url,
                "gitRef": valid_ref or "",
                "empty": True,
            }
            (output_dir / "knowledge-manifest.json").write_text(
                json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            return manifest
        source = Path(fetch_info["repoPath"])
    if source is not None:
        pack_dir = output_dir / "pack"
        if pack_dir.exists():
            shutil.rmtree(pack_dir)
        pack_dir.mkdir(parents=True, exist_ok=True)
        for src in iter_docs(source):
            rel = src.relative_to(source)
            dest = pack_dir / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
            copied += 1
            rows.append({
                "title": title_of(src).replace("|", "/"),
                "dimension": infer_dimension(str(rel)),
                "path": str(Path("pack") / rel),
                "source": str(source),
            })
    source_label = str(source) if source else ""
    if git_url and fetch_info:
        source_label = fetch_info.get("url") or git_url
    index_path = write_index(output_dir, rows, source_label)
    manifest = {
        "ok": True,
        "indexPath": str(index_path),
        "entryCount": len(rows),
        "copied": copied,
        "source": str(source) if source else "",
        "gitUrl": (fetch_info or {}).get("url", ""),
        "gitRef": (fetch_info or {}).get("ref", ""),
        "empty": not rows,
    }
    (output_dir / "knowledge-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate knowledge/index.md from a local directory or user Git URL")
    parser.add_argument("--output-dir", required=True, help="{run_dir}/knowledge")
    parser.add_argument("--source", default="", help="User-provided local knowledge directory; may be empty")
    parser.add_argument("--git-url", default="", help="Explicit knowledge-repo Git URL from the user; may be empty")
    parser.add_argument("--git-ref", default="", help="Optional branch or tag")
    args = parser.parse_args()

    output_dir = Path(args.output_dir).expanduser().resolve()
    source = Path(args.source).expanduser().resolve() if args.source else None
    if source is not None and not source.is_dir():
        print(json.dumps({
            "ok": False,
            "error": "SOURCE_DIR_NOT_FOUND",
            "msg": "Knowledge directory does not exist or is not a directory: %s" % source,
            "indexPath": "",
            "entryCount": 0,
            "empty": True,
        }, ensure_ascii=False, indent=2, sort_keys=True))
        return 1

    manifest = bootstrap(output_dir, source, git_url=args.git_url, git_ref=args.git_ref)
    lines = [
        "index=%s" % manifest["indexPath"],
        "entries=%d" % manifest["entryCount"],
    ]
    if not manifest.get("ok"):
        lines.append("ERROR: %s" % manifest.get("error", "bootstrap failed"))
    if manifest.get("empty"):
        lines.append("empty=1")
    print(json.dumps({
        **manifest,
        "msg": "\n".join(lines),
    }, ensure_ascii=False, indent=2, sort_keys=True))
    return 0 if manifest.get("ok") else 1


if __name__ == "__main__":
    sys.exit(main())
